DATA SEGMENT
	N1 DW 2134H
	N2 DW 1111H
	SUBT DW ?
DATA ENDS
CODE SEGMENT
	ASSUME CS:CODE, DS:DATA
		START : MOV AX, DATA
				MOV DS,AX
				MOV AX,N1
				SUB AX,N2
				MOV SUBT,AX
				INT 3
		CODE ENDS
END START